name: 'Terraform'

on:
  push:
    branches: [ "master" ]
    paths: Terraform/**
    types:
      - completed

permissions:
  contents: read
env:
  TF_VAR_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_aws_region: ${{ secrets.AWS_REGION }} 
  apigateway_url: ${{ secrets.APIGATEWAY_URL }} 
  lb_url: ${{ secrets.LB_URL }} 
  
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        shell: bash
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
  
      - 
        name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
  
      - 
        name: Terraform Init
        working-directory: Terraform/
        run: terraform init
  
      - 
        name: Terraform Format
        working-directory: Terraform/
        run: terraform fmt -check
  
      - 
        name: Terraform Plan
        working-directory: Terraform/
        run: terraform plan -input=false
           
       - 
         name: Terraform Apply
         working-directory: Terraform/
         if: github.ref == 'refs/heads/"master"' && github.event_name == 'push'
         run: terraform apply -auto-approve -input=false
